services:
  - postgresql
before_script:
  - psql -c 'create database bucketlist_api;' -U postgres
language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"

script:
  - nosetests --cover-package=bucketlist --with-coverage
after_success:
  coveralls
