services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U flask
language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
# command to run tests
script:
  - nosetests --cover-package=bucketlist --with-coverage
after_success:
  coveralls
